### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by EionRobb** [BlueWinds/pidgin-irc-format#5]
Happy to see someone taking the old plugin over, but can you please use a GPL-compatible licence, and not claim copyright :)

**Comment by BlueWinds** [comment]
@EionRobb - Ah, the copyright is for the license (which I didn't write), not the work itself, sorry that's unclear. Definitely didn't mean to claim this for myself!

"This is a lax permissive non-copyleft free software license, compatible with the GNU GPL."
http://www.gnu.org/licenses/license-list.html#WTFPL

I'd be happy to replace it with a license of your choice, I just didn't see one on the original repo (maybe I missed it).

**Comment by EionRobb** [comment]
OIC :)

**Comment by kgraefe** [comment]
According to [Google Code](https://code.google.com/p/pidgin-irc-format/) the code should be under GPLv2: ![Unbenannt](https://user-images.githubusercontent.com/3797324/70922812-08b34080-2027-11ea-8d08-825f30362563.png)

**Comment by BlueWinds** [comment]
Changed, thanks for the info.

(to be clear, I didn't make this change 4 years ago because the original author closed their own ticket, not because I disagreed / didn't care. :) )
